gantt
    title Course Capstone Project
    dateFormat  DD/MM
    axisFormat  %d/%m
    section Introduction
        1-MsProject Tutorial : c1, 18/10, 7d
        2-Project stakeholders :c2, after c1  , 7d
        3-Proposal governance :c3, after c2, 7d

    section Project Plan
        Task in sec      :c4, after c3  , 5d
        another task      : 24d